AWS_PROFILE=default
corpus_dir?=/scratch/lustre/home/hpc_airenas/train-asr/corpus/LIEPA3
common_voice_download_dir?=/scratch/lustre/home/hpc_airenas/train-asr/corpus
gpus?=4
## increase if gpu mem allows
max_duration?=1000
seconds_train_kmeans?=360000
epoch_train?=30
avg?=10
data_dir?=/scratch/lustre/home/hpc_airenas/train-asr/experiments/VietASR
exp_dir?=/scratch/lustre/home/hpc_airenas/train-asr/experiments/VietASR/exp/v01rts
pretrain_exp_dir?=/scratch/lustre/home/hpc_airenas/train-asr/experiments/VietASR/exp/pretrain_v01
finetune_exp_dir?=/scratch/lustre/home/hpc_airenas/train-asr/experiments/VietASR/exp/finetune_v01
epoch_pretrain?=100
train_fbank_dir?=/scratch/lustre/home/hpc_airenas/train-asr/experiments/VietASR/fbank-fixed
icefall_dir?=/workspace/icefall/
model_params?=--num-encoder-layers 2,2,3,4,3,2 \
		--feedforward-dim 512,768,1024,1536,1024,768 \
		--encoder-dim 192,256,384,512,384,256 \
		--encoder-unmasked-dim 192,192,256,256,256,192 \
		--use-ctc 1 --use-transducer 1 --causal 1


